const mongoose = require("mongoose");
const Customer = require("./models/Customer");
const Product = require("./models/Product");
const Service = require("./models/Service");
const Rate = require("./models/Rate");
const Estimate = require("./models/Estimate");
const Quotation = require("./models/Quotation");
const ProformaInvoice = require("./models/ProformaInvoice");
const Invoice = require("./models/Invoice");
const DeliveryChallan = require("./models/DeliveryChallan");
const Payment = require("./models/Payment");
const Setting = require("./models/Setting");
const User = require("./models/User");

const seedDatabase = async () => {
  try {
    console.log("Seeding Glass Billing database...");

    // Clear existing collections
    await Promise.all([
      Customer.deleteMany({}),
      Product.deleteMany({}),
      Service.deleteMany({}),
      Rate.deleteMany({}),
      Estimate.deleteMany({}),
      Quotation.deleteMany({}),
      ProformaInvoice.deleteMany({}),
      Invoice.deleteMany({}),
      DeliveryChallan.deleteMany({}),
      Payment.deleteMany({}),
      Setting.deleteMany({}),
      User.deleteMany({}),
    ]);

    // 0. Demo User for quick login
    await User.create({
      name: "Admin Farzan",
      email: "admin@crystalglass.com",
      password: "admin1234",
      role: "owner",
      businessCompleted: true,
      business: {
        companyName: "Crystal Glass & Glazing Solutions",
        tagline: "Precision Architectural & Toughened Glass Works",
        phone: "+91 98200 45678",
        email: "billing@crystalglass.com",
        gstin: "27AABCC9876R1ZX",
        pan: "AABCC9876R",
        address: "Unit 14-16, Glass Tech Industrial Estate, Kherani Road, Sakinaka",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400072",
        bankName: "HDFC Bank Ltd",
        accountNumber: "50200055443322",
        ifscCode: "HDFC0000123",
        branch: "Sakinaka Branch, Mumbai",
        upiId: "crystalglass@okhdfcbank",
        defaultUnit: "inch",
        minChargeableArea: 1.0,
        roundDimensionsToInch: true,
        defaultGstRate: 18,
        invoicePrefix: "INV-",
        estimatePrefix: "EST-",
        quotationPrefix: "QT-",
        challanPrefix: "DC-",
        receiptPrefix: "RCPT-",
        termsAndConditions:
          "1. All dimensions must be confirmed in writing or template approval before cutting/toughening.\n2. No cancellation once glass is processed in furnace.\n3. Breaking during transport or site installation is at buyer's risk unless transit insurance is billed.\n4. Standard tolerance ±2mm on CNC cutting.\n5. Payment strictly 50% advance, balance on delivery.",
      },
    });

    // 1. Settings
    const setting = await Setting.create({
      companyName: "Crystal Glass & Glazing Solutions",
      tagline: "Precision Architectural & Toughened Glass Works",
      phone: "+91 98200 45678",
      email: "billing@crystalglass.com",
      gstin: "27AABCC9876R1ZX",
      pan: "AABCC9876R",
      address: "Unit 14-16, Glass Tech Industrial Estate, Kherani Road, Sakinaka",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400072",
      bankName: "HDFC Bank Ltd",
      accountNumber: "50200055443322",
      ifscCode: "HDFC0000123",
      branch: "Sakinaka Branch, Mumbai",
      upiId: "crystalglass@okhdfcbank",
      defaultUnit: "inch",
      minChargeableArea: 1.0,
      roundDimensionsToInch: true,
      defaultGstRate: 18,
      invoicePrefix: "INV-",
      estimatePrefix: "EST-",
      quotationPrefix: "QT-",
      challanPrefix: "DC-",
      receiptPrefix: "RCPT-",
      termsAndConditions:
        "1. All dimensions must be confirmed in writing or template approval before cutting/toughening.\n2. No cancellation once glass is processed in furnace.\n3. Breaking during transport or site installation is at buyer's risk unless transit insurance is billed.\n4. Standard tolerance ±2mm on CNC cutting.\n5. Payment strictly 50% advance, balance on delivery.",
    });

    // 2. Customers
    const customers = await Customer.create([
      {
        name: "Rajesh Singhania",
        company: "Apex Luxury Towers & Facades",
        phone: "+91 98201 12345",
        email: "procurement@apextowers.in",
        gstin: "27AACCA1234F1Z8",
        address: "702, Skyline Corporate Park, Andheri East",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400069",
        category: "Contractor",
        creditLimit: 250000,
        balance: 42500,
        notes: "Major contractor for high-rise railing glass and shower cubicles.",
      },
      {
        name: "Pooja Mehta",
        company: "Vogue Interior Architecture Studio",
        phone: "+91 98199 54321",
        email: "pooja@vogueinteriors.com",
        gstin: "27AABCV8821N1ZM",
        address: "Lane 5, Koregaon Park",
        city: "Pune",
        state: "Maharashtra",
        pincode: "411001",
        category: "Architect",
        creditLimit: 150000,
        balance: 0,
        notes: "Specifies tinted mirrors, fluted partitions, and lacquered glass panels.",
      },
      {
        name: "Irfan Khan",
        company: "Royal Aluminum & Glazing Works",
        phone: "+91 98210 98765",
        email: "irfan.royalglass@gmail.com",
        gstin: "27AAPCR4432K1ZP",
        address: "Gala 8, Mumbra Industrial Area",
        city: "Thane",
        state: "Maharashtra",
        pincode: "400612",
        category: "Fabricator",
        creditLimit: 100000,
        balance: 18400,
        notes: "Regular weekly buyer of 5mm, 8mm, and 12mm clear toughened glass.",
      },
      {
        name: "Suresh Agarwal",
        company: "Metro Glass Traders & Wholesale",
        phone: "+91 98333 45678",
        email: "metroglass.vashi@yahoo.com",
        gstin: "27AAGCM9988D1Z2",
        address: "Sector 19C, APMC Market, Vashi",
        city: "Navi Mumbai",
        state: "Maharashtra",
        pincode: "400703",
        category: "Wholesaler",
        creditLimit: 500000,
        balance: 75000,
        notes: "Buys in bulk crate loads. Eligible for wholesale tier rates.",
      },
      {
        name: "Karan Johar Residency",
        company: "Individual Villa Project",
        phone: "+91 99200 33445",
        email: "karan.residence@gmail.com",
        gstin: "",
        address: "12 Carter Road, Bandra West",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400050",
        category: "Retailer",
        creditLimit: 30000,
        balance: 0,
        notes: "Walk-in client for 10mm bathroom shower cubicle with gold hardware cutouts.",
      },
    ]);

    // 3. Products
    const products = await Product.create([
      {
        name: "5mm Clear Float Glass",
        category: "Clear Float",
        thickness: 5,
        baseRate: 46,
        minChargeableArea: 1.0,
        hsnCode: "7005",
        inStock: true,
        stockSqFt: 4500,
        description: "High clarity Saint-Gobain float glass, distortion free.",
      },
      {
        name: "8mm Toughened Clear Glass",
        category: "Toughened / Tempered",
        thickness: 8,
        baseRate: 105,
        minChargeableArea: 1.0,
        hsnCode: "7007",
        inStock: true,
        stockSqFt: 3200,
        description: "Grade-A thermally tempered safety glass for partitions and windows.",
      },
      {
        name: "10mm Toughened Clear Glass",
        category: "Toughened / Tempered",
        thickness: 10,
        baseRate: 135,
        minChargeableArea: 1.0,
        hsnCode: "7007",
        inStock: true,
        stockSqFt: 2800,
        description: "Ideal for frameless shower enclosures and office cabin partitions.",
      },
      {
        name: "12mm Toughened Clear Glass",
        category: "Toughened / Tempered",
        thickness: 12,
        baseRate: 165,
        minChargeableArea: 1.5,
        hsnCode: "7007",
        inStock: true,
        stockSqFt: 2100,
        description: "Heavy duty architectural glass for entrance doors, patch fittings, and glass railings.",
      },
      {
        name: "5mm Bronze Tinted Glass",
        category: "Tinted Glass",
        thickness: 5,
        baseRate: 68,
        minChargeableArea: 1.0,
        hsnCode: "7005",
        inStock: true,
        stockSqFt: 1400,
        description: "Solar control body tinted float glass with warm bronze hue.",
      },
      {
        name: "5mm Belgian Silver Mirror",
        category: "Mirror / Silvered",
        thickness: 5,
        baseRate: 78,
        minChargeableArea: 1.0,
        hsnCode: "7009",
        inStock: true,
        stockSqFt: 1800,
        description: "Copper-free lead-free corrosion-resistant high definition mirror.",
      },
      {
        name: "10mm Frosted Acid Etched Glass",
        category: "Frosted / Acid Etched",
        thickness: 10,
        baseRate: 175,
        minChargeableArea: 1.0,
        hsnCode: "7006",
        inStock: true,
        stockSqFt: 950,
        description: "Silky matte translucent finish, fingerprint resistant for privacy partitions.",
      },
      {
        name: "8mm Fluted / Reeded Glass",
        category: "Fluted / Reeded",
        thickness: 8,
        baseRate: 210,
        minChargeableArea: 1.0,
        hsnCode: "7003",
        inStock: true,
        stockSqFt: 800,
        description: "Textured fluted architectural glass with optical ribbed pattern.",
      },
      {
        name: "11.52mm Laminated Safety Glass (5+1.52PVB+5)",
        category: "Laminated Safety",
        thickness: 11.52,
        baseRate: 260,
        minChargeableArea: 1.5,
        hsnCode: "7007",
        inStock: true,
        stockSqFt: 1100,
        description: "Acoustic and impact safety laminated glass for balconies and skylights.",
      },
      {
        name: "4mm Lacquered Black Glass",
        category: "Lacquered Glass",
        thickness: 4,
        baseRate: 135,
        minChargeableArea: 1.0,
        hsnCode: "7006",
        inStock: true,
        stockSqFt: 600,
        description: "Opaque back-painted colored glass for luxury kitchen splashbacks & wardrobes.",
      },
    ]);

    // 4. Services
    const services = await Service.create([
      {
        name: "Flat Machine Edge Polish",
        code: "FLAT_POLISH",
        chargeType: "per_rft",
        rate: 15,
        unit: "Rft",
        description: "High-speed CNC diamond wheel edge polish with arris.",
        isActive: true,
      },
      {
        name: "1-Inch Beveling Polish",
        code: "BEVEL_1INCH",
        chargeType: "per_rft",
        rate: 35,
        unit: "Rft",
        description: "Decorative 25mm beveled edge for mirrors and tabletops.",
        isActive: true,
      },
      {
        name: "Pencil / Round Edge Polish",
        code: "PENCIL_POLISH",
        chargeType: "per_rft",
        rate: 18,
        unit: "Rft",
        description: "Smooth C-profile rounded edge for tabletops and open shelves.",
        isActive: true,
      },
      {
        name: "Hole Drilling (12mm - 25mm)",
        code: "HOLE_DRILL",
        chargeType: "per_hole",
        rate: 40,
        unit: "Hole",
        description: "Water-cooled diamond core drill for hinges, handles, and patch fittings.",
        isActive: true,
      },
      {
        name: "Patch Fitting / Corner Cutout",
        code: "CORNER_CUTOUT",
        chargeType: "per_cutout",
        rate: 150,
        unit: "Cutout",
        description: "CNC waterjet cutout with polished radiused inner corners for glass door fittings.",
        isActive: true,
      },
      {
        name: "Sandblast / Chemical Frosting",
        code: "FROSTING_WORK",
        chargeType: "per_sqft",
        rate: 25,
        unit: "Sq.Ft",
        description: "Uniform translucent frosting or custom stencil design.",
        isActive: true,
      },
      {
        name: "Safety Film Application",
        code: "SAFETY_FILM",
        chargeType: "per_sqft",
        rate: 30,
        unit: "Sq.Ft",
        description: "4-mil anti-shatter explosion proof film application.",
        isActive: true,
      },
    ]);

    // 5. Rates Master Tiers
    await Rate.create([
      {
        name: "Standard Retail Price Matrix",
        tier: "Retailer",
        discountPercent: 0,
        roundToNextInch: true,
        minChargeableArea: 1.0,
        notes: "Standard walk-in customer pricing.",
      },
      {
        name: "Contractor Partner Tier",
        tier: "Contractor",
        discountPercent: 12,
        roundToNextInch: true,
        minChargeableArea: 1.0,
        notes: "Approved rate list for registered civil and interior contractors.",
      },
      {
        name: "Architect & Designer Preferred Matrix",
        tier: "Architect",
        discountPercent: 15,
        roundToNextInch: false,
        minChargeableArea: 1.0,
        notes: "Specifier discounts for architecture practices.",
      },
      {
        name: "Wholesale Bulk Distributor Tier",
        tier: "Wholesaler",
        discountPercent: 20,
        roundToNextInch: true,
        minChargeableArea: 1.0,
        notes: "Full crate volume discounts.",
      },
    ]);

    // 6. Estimates
    const estimate1 = await Estimate.create({
      estimateNumber: "EST-2026-0001",
      customer: {
        id: customers[0]._id,
        name: customers[0].name,
        company: customers[0].company,
        phone: customers[0].phone,
        gstin: customers[0].gstin,
        address: customers[0].address,
      },
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      validUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      dimensionUnit: "inch",
      items: [
        {
          description: "Main Entrance Toughened Door",
          glassType: "12mm Toughened Clear Glass",
          thickness: 12,
          width: 36,
          height: 84,
          quantity: 2,
          areaSqFt: 21.0,
          totalAreaSqFt: 42.0,
          glassRate: 165,
          glassAmount: 6930,
          services: [
            { serviceName: "Flat Machine Edge Polish", chargeType: "per_rft", rate: 15, quantity: 40, amount: 600 },
            { serviceName: "Patch Fitting / Corner Cutout", chargeType: "per_cutout", rate: 150, quantity: 4, amount: 600 },
            { serviceName: "Hole Drilling (12mm - 25mm)", chargeType: "per_hole", rate: 40, quantity: 4, amount: 160 },
          ],
          servicesAmount: 1360,
          itemTotal: 8290,
        },
        {
          description: "Fixed Partition Side Glass",
          glassType: "12mm Toughened Clear Glass",
          thickness: 12,
          width: 48,
          height: 84,
          quantity: 2,
          areaSqFt: 28.0,
          totalAreaSqFt: 56.0,
          glassRate: 165,
          glassAmount: 9240,
          services: [
            { serviceName: "Flat Machine Edge Polish", chargeType: "per_rft", rate: 15, quantity: 44, amount: 660 },
          ],
          servicesAmount: 660,
          itemTotal: 9900,
        },
      ],
      subtotal: 18190,
      discountPercent: 5,
      discountAmount: 909.5,
      taxRate: 18,
      taxAmount: 3110.49,
      transportCharges: 1200,
      roundOff: -0.99,
      grandTotal: 21590,
      status: "Approved",
      notes: "Door hardware cutouts as per Ozone OPF-10 template provided.",
    });

    const estimate2 = await Estimate.create({
      estimateNumber: "EST-2026-0002",
      customer: {
        id: customers[1]._id,
        name: customers[1].name,
        company: customers[1].company,
        phone: customers[1].phone,
        gstin: customers[1].gstin,
        address: customers[1].address,
      },
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      validUntil: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000),
      dimensionUnit: "inch",
      items: [
        {
          description: "Vanity Decorative Mirror",
          glassType: "5mm Belgian Silver Mirror",
          thickness: 5,
          width: 30,
          height: 48,
          quantity: 3,
          areaSqFt: 10.0,
          totalAreaSqFt: 30.0,
          glassRate: 78,
          glassAmount: 2340,
          services: [
            { serviceName: "1-Inch Beveling Polish", chargeType: "per_rft", rate: 35, quantity: 39, amount: 1365 },
          ],
          servicesAmount: 1365,
          itemTotal: 3705,
        },
      ],
      subtotal: 3705,
      discountPercent: 0,
      discountAmount: 0,
      taxRate: 18,
      taxAmount: 666.9,
      transportCharges: 500,
      roundOff: 0.1,
      grandTotal: 4872,
      status: "Draft",
      notes: "Packed in individual bubble film sleeves.",
    });

    // 7. Quotations
    const quotation1 = await Quotation.create({
      quotationNumber: "QT-2026-0001",
      estimateRef: "EST-2026-0001",
      customer: {
        id: customers[0]._id,
        name: customers[0].name,
        company: customers[0].company,
        phone: customers[0].phone,
        gstin: customers[0].gstin,
        address: customers[0].address,
      },
      date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      validUntil: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
      dimensionUnit: "inch",
      items: estimate1.items,
      subtotal: 18190,
      discountPercent: 5,
      discountAmount: 909.5,
      taxRate: 18,
      taxAmount: 3110.49,
      transportCharges: 1200,
      roundOff: -0.99,
      grandTotal: 21590,
      status: "Accepted",
      terms: [
        "Prices are inclusive of standard wooden crate packaging.",
        "50% advance along with order confirmation, balance on delivery.",
        "Breakage liability ceases once glass is unloaded at site.",
        "Standard tolerance ±2mm.",
      ],
      notes: "Approved by Rajesh Singhania on WhatsApp.",
    });

    // 8. Proforma Invoices
    const proforma1 = await ProformaInvoice.create({
      proformaNumber: "PI-2026-0001",
      quotationRef: "QT-2026-0001",
      customer: {
        id: customers[0]._id,
        name: customers[0].name,
        company: customers[0].company,
        phone: customers[0].phone,
        gstin: customers[0].gstin,
        address: customers[0].address,
      },
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      dimensionUnit: "inch",
      items: quotation1.items,
      subtotal: 18190,
      discountAmount: 909.5,
      taxRate: 18,
      taxAmount: 3110.49,
      transportCharges: 1200,
      roundOff: -0.99,
      grandTotal: 21590,
      advanceRequiredPercent: 50,
      advanceAmount: 10795,
      advancePaid: 10795,
      balanceDue: 10795,
      status: "Confirmed",
      bankDetails: {
        bankName: "HDFC Bank Ltd",
        accountNumber: "50200055443322",
        ifscCode: "HDFC0000123",
        upiId: "crystalglass@okhdfcbank",
      },
      notes: "Advance ₹10,795 received via NEFT on 22nd.",
    });

    // 9. Invoices
    const invoice1 = await Invoice.create({
      invoiceNumber: "INV-2026-0001",
      invoiceType: "Tax Invoice",
      date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
      customer: {
        id: customers[0]._id,
        name: customers[0].name,
        company: customers[0].company,
        phone: customers[0].phone,
        gstin: customers[0].gstin,
        address: customers[0].address,
        city: customers[0].city,
        state: customers[0].state,
      },
      placeOfSupply: "Maharashtra (27)",
      vehicleNumber: "MH-04-AB-1234",
      dimensionUnit: "inch",
      items: [
        {
          description: "12mm Toughened Balcony Railing Panels",
          glassType: "12mm Toughened Clear Glass",
          thickness: 12,
          hsnCode: "7007",
          width: 48,
          height: 42,
          quantity: 6,
          areaSqFt: 14.0,
          totalAreaSqFt: 84.0,
          glassRate: 165,
          glassAmount: 13860,
          services: [
            { serviceName: "Flat Machine Edge Polish", chargeType: "per_rft", rate: 15, quantity: 90, amount: 1350 },
            { serviceName: "Hole Drilling (12mm - 25mm)", chargeType: "per_hole", rate: 40, quantity: 24, amount: 960 },
          ],
          servicesAmount: 2310,
          itemTotal: 16170,
        },
      ],
      subtotal: 16170,
      discountAmount: 0,
      taxableAmount: 16170,
      gstRate: 18,
      cgst: 1455.3,
      sgst: 1455.3,
      igst: 0,
      transportCharges: 1500,
      roundOff: 0.4,
      grandTotal: 20581,
      amountPaid: 20581,
      balanceDue: 0,
      paymentStatus: "Paid",
      challanCreated: true,
      notes: "Delivered to site tower B.",
      terms: "Full payment received.",
    });

    const invoice2 = await Invoice.create({
      invoiceNumber: "INV-2026-0002",
      invoiceType: "Tax Invoice",
      date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
      customer: {
        id: customers[2]._id,
        name: customers[2].name,
        company: customers[2].company,
        phone: customers[2].phone,
        gstin: customers[2].gstin,
        address: customers[2].address,
        city: customers[2].city,
        state: customers[2].state,
      },
      placeOfSupply: "Maharashtra (27)",
      vehicleNumber: "MH-02-EE-9988",
      dimensionUnit: "inch",
      items: [
        {
          description: "8mm Clear Toughened Window Panes",
          glassType: "8mm Toughened Clear Glass",
          thickness: 8,
          hsnCode: "7007",
          width: 36,
          height: 60,
          quantity: 4,
          areaSqFt: 15.0,
          totalAreaSqFt: 60.0,
          glassRate: 105,
          glassAmount: 6300,
          services: [
            { serviceName: "Flat Machine Edge Polish", chargeType: "per_rft", rate: 15, quantity: 64, amount: 960 },
          ],
          servicesAmount: 960,
          itemTotal: 7260,
        },
      ],
      subtotal: 7260,
      discountAmount: 0,
      taxableAmount: 7260,
      gstRate: 18,
      cgst: 653.4,
      sgst: 653.4,
      igst: 0,
      transportCharges: 800,
      roundOff: 0.2,
      grandTotal: 9367,
      amountPaid: 5000,
      balanceDue: 4367,
      paymentStatus: "Partial",
      challanCreated: true,
      notes: "Partial payment ₹5,000 via UPI. Balance on final fitment.",
    });

    const invoice3 = await Invoice.create({
      invoiceNumber: "INV-2026-0003",
      invoiceType: "Tax Invoice",
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      customer: {
        id: customers[3]._id,
        name: customers[3].name,
        company: customers[3].company,
        phone: customers[3].phone,
        gstin: customers[3].gstin,
        address: customers[3].address,
        city: customers[3].city,
        state: customers[3].state,
      },
      placeOfSupply: "Maharashtra (27)",
      vehicleNumber: "MH-43-AK-4455",
      dimensionUnit: "inch",
      items: [
        {
          description: "5mm Clear Float Glass Crates (Bulk)",
          glassType: "5mm Clear Float Glass",
          thickness: 5,
          hsnCode: "7005",
          width: 72,
          height: 96,
          quantity: 15,
          areaSqFt: 48.0,
          totalAreaSqFt: 720.0,
          glassRate: 46,
          glassAmount: 33120,
          services: [],
          servicesAmount: 0,
          itemTotal: 33120,
        },
      ],
      subtotal: 33120,
      discountAmount: 1656,
      taxableAmount: 31464,
      gstRate: 18,
      cgst: 2831.76,
      sgst: 2831.76,
      igst: 0,
      transportCharges: 2500,
      roundOff: -0.52,
      grandTotal: 39627,
      amountPaid: 0,
      balanceDue: 39627,
      paymentStatus: "Unpaid",
      challanCreated: false,
      notes: "Full crate delivery. Forklift required at Vashi unloading dock.",
    });

    // 10. Delivery Challans
    const challan1 = await DeliveryChallan.create({
      challanNumber: "DC-2026-0001",
      invoiceRef: "INV-2026-0001",
      customer: {
        id: customers[0]._id,
        name: customers[0].name,
        company: customers[0].company,
        phone: customers[0].phone,
        address: customers[0].address,
      },
      date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
      shippingAddress: "Site: Skyline Corporate Park Tower B, Andheri East",
      vehicleNumber: "MH-04-AB-1234",
      driverName: "Suresh Yadav",
      driverPhone: "+91 98200 77665",
      items: [
        {
          description: "12mm Toughened Balcony Railing Panels with 4 Holes",
          glassType: "12mm Toughened Clear Glass",
          thickness: 12,
          width: 48,
          height: 42,
          unit: "inch",
          quantity: 6,
          sqFt: 84.0,
          remarks: "Polished edges with corner protection caps",
        },
      ],
      totalPieces: 6,
      totalSqFt: 84.0,
      status: "Delivered",
      dispatchedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
      deliveredAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      recipientName: "Site Engineer Anil Patil",
      notes: "Received in sound condition with glass racks intact.",
    });

    const challan2 = await DeliveryChallan.create({
      challanNumber: "DC-2026-0002",
      invoiceRef: "INV-2026-0002",
      customer: {
        id: customers[2]._id,
        name: customers[2].name,
        company: customers[2].company,
        phone: customers[2].phone,
        address: customers[2].address,
      },
      date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      shippingAddress: "Gala 8, Mumbra Industrial Area, Thane",
      vehicleNumber: "MH-02-EE-9988",
      driverName: "Ramesh Pawar",
      driverPhone: "+91 97690 33441",
      items: [
        {
          description: "8mm Clear Toughened Window Panes",
          glassType: "8mm Toughened Clear Glass",
          thickness: 8,
          width: 36,
          height: 60,
          unit: "inch",
          quantity: 4,
          sqFt: 60.0,
          remarks: "Flat machine polish on all 4 sides",
        },
      ],
      totalPieces: 4,
      totalSqFt: 60.0,
      status: "In Transit",
      dispatchedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      notes: "Expected delivery today before 6 PM.",
    });

    // 11. Payments
    await Payment.create([
      {
        receiptNumber: "RCPT-2026-0001",
        customer: {
          id: customers[0]._id,
          name: customers[0].name,
          company: customers[0].company,
        },
        invoiceNumber: "INV-2026-0001",
        invoiceId: invoice1._id,
        amount: 20581,
        date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        paymentMethod: "NEFT/RTGS",
        referenceNumber: "HDFCN2609871234",
        notes: "Full settlement for invoice INV-2026-0001.",
      },
      {
        receiptNumber: "RCPT-2026-0002",
        customer: {
          id: customers[2]._id,
          name: customers[2].name,
          company: customers[2].company,
        },
        invoiceNumber: "INV-2026-0002",
        invoiceId: invoice2._id,
        amount: 5000,
        date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
        paymentMethod: "UPI",
        referenceNumber: "UPI/324109887766/PayTM",
        notes: "Advance part payment against invoice INV-2026-0002.",
      },
      {
        receiptNumber: "RCPT-2026-0003",
        customer: {
          id: customers[0]._id,
          name: customers[0].name,
          company: customers[0].company,
        },
        invoiceNumber: "PI-2026-0001",
        amount: 10795,
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        paymentMethod: "NEFT/RTGS",
        referenceNumber: "HDFCN2609998877",
        notes: "50% advance for Proforma PI-2026-0001.",
      },
    ]);

    console.log("Database seeded successfully with rich glass billing data!");
    return { success: true, message: "Database seeded successfully" };
  } catch (error) {
    console.error("Seeding error:", error);
    throw error;
  }
};

module.exports = seedDatabase;

if (require.main === module) {
  require("dotenv").config();
  const connectDB = require("./config/database");
  connectDB().then(async () => {
    await seedDatabase();
    process.exit(0);
  });
}
